### ISSUE TITLE
Password Prompt

### ISSUE THREAD

**Issue by rajshah4** [ermaker/dockerfile-keras-jupyter#2]
When I start up the latest docker image, I get a prompt for a jupyter notebook password.  Is there a default password to use?  Is it possible to set a password on the command line when I launch docker?  . . . thanks

**Comment by ermaker** [comment]
Hello,
I found the changes of jupyter which you told. I will check the settings.

**Comment by ermaker** [comment]
@rajshah4 I pushed the changes and it works for me. Please check the latest docker image.

**Comment by rajshah4** [comment]
Thanks, its works for me now
